### ISSUE TITLE
'Studio' Icons

### ISSUE THREAD

**Issue by MichaelDanninger** [seothemes/icon-widget#2]
Love this plugin, simply useful, amazing work. But one 'issue', on the seothemes website there are nice icons in a theme called 'studio pro' – can these be added? I'm not into plugin development, just themes. :(

**Comment by seothemes** [comment]
Hi @MrMchaD 

The icon font used on seothemes.com is [Line Awesome](https://icons8.com/line-awesome).

This is already included in the plugin. You can select the font from **Settings > Icon Widget**.
